### ISSUE TITLE
Is there a way to use external component?

### ISSUE THREAD

**Issue by muratmarkaryan** [FormidableLabs/react-live#106]
I try to use custom component that is already imported. When i try to use below example i got an error (Welcome is not defined!) but i already use in same component where LiveProvider already located. 

`<Welcome name="John"></Welcome>`

**Comment by kitten** [comment]
All code on react-live is run in isolation. Your code is just a string and everything that's in scope of the string will not be available when said code is run.

That's why we accept the scope prop using which you can inject variables that your code can the see: https://github.com/FormidableLabs/react-live/blob/master/README.md#how-does-the-scope-work

So in your case you'd simply pass your Welcome component into the scope prop.
