### ISSUE TITLE
variable outside Component is not working

### ISSUE THREAD

**Issue by wulucxy** [FormidableLabs/react-live#119]
@kitten 

the problem is here：

```javascript
var stockData = [{date:24-Apr-07,close:93.24},{date:25-Apr-07,close:95.35},{date:26-Apr-07,close:98.84},{date:27-Apr-07,close:99.92},{date:30-Apr-07,close:99.8}]

class Demo1 extends React.Component {
   render(){
      // render something
   }
}
```

it will throw an error：

```javascript
SyntaxError: Unexpected token (1:1) 1 : (var stockData = [{ ^
```

**Comment by kitten** [comment]
So multiple issues here, that's not valid JS, since some things here should be strings, but assuming that's just due to the lack of a better example you need to set the `noInline` prop to `true` and use `render` to actually render the component. That's because this is not just an inline expression, but a full piece of code.

You can see an example of that on the demo site. The last example is set to `noInline` mode: https://react-live.kitten.sh/

**Comment by iamskok** [comment]
@kitten can you please update your demo? The link you shared is broken :(

**Comment by sofiapoh** [comment]
@iamskok This demo is now viewable [here](https://react-live.netlify.com/)
