### ISSUE TITLE
how to ignore import & require statement

### ISSUE THREAD

**Issue by wulucxy** [FormidableLabs/react-live#121]
@kitten as a npm package，we always have to import third packages，like so：

```javascript
import {get} from 'lodash'

class Demo1 extends React.Component {
  render () {
    // do something with get
  }
}
```

actually，we prefer to use  scope to pass global variables。and this will throw an error。

so do you have some support on such an ignore statement?

**Comment by mathieudutour** [comment]
you can use the `transformCode` props on LiveProvider:
```js
const importRegex = /import(?:["'\s]*([\w*{}\n, ]+)from\s*)["'\s]*([@\w/_-]+)["'\s]*;?/gm
const requireRegex = /(const|let|var)\s*([\w{}\n, ]+\s*)=\s*require\s*\(["'\s]*([@\w/_-]+)["'\s]*\s*\);?/gm
const imports = {
 lodash: 'Lodash'
}

const transformCode = (code) => {
  return code.replace(importRegex, (match, p1, p2) => {
    const matchingImport = imports[p2]
    if (!matchingImport) {
      // leave it alone if we don't have a matching import
      return match
    }

    return 'var ' + p1 + ' = ' + matchingImport + ';'
  })
  .replace(requireRegex, (match, p1, p2, p3) => {
    const matchingImport = imports[p2]
    if (!matchingImport) {
      // leave it alone if we don't have a matching import
      return match
    }

    return p1 + ' ' + p2 + ' = ' + matchingImport + ';'
  })
}
```

and pass `Lodash` in the scope

**Comment by wulucxy** [comment]
the regex is so annoying......

**Comment by mathieudutour** [comment]
you're welcome?

**Comment by wulucxy** [comment]
@mathieudutour thanks for your reply。this works，but these are still options to consider:

1. import {xx} from 'xx'
2. import xx from 'xx'
3. import xx from './xx'
4. var data = require('./data')

3，4 are not suitable for regex。can you integrate this feature?

**Comment by kitten** [comment]
@wulucxy: I don't think it'd make sense to not write this yourself, at least since you know your constraints and requirements best.

We've just added an example to use Babel in transformCode. This could make it easier to solve but you'd also take on a larger bundle size.

You could also modify the regex and strip out every line that simply starts with "import".

A solution for require would be to pass it onto the scope and simply return undefined if the result doesn't matter. Either way, that's luckily just a function call.

**Comment by wulucxy** [comment]
@kitten thanks for the reply。
