### ISSUE TITLE
support IE11?

### ISSUE THREAD

**Issue by anuoua** [FormidableLabs/react-live#137]
I want to use it with ie11, but there are some wrong here.

**Comment by sofiapoh** [comment]
Hi, making this project work on IE11 is not really currently on my radar but if you'd be able to provide more detail of what exactly isn't working or submit a PR for the changes required please do so!

**Comment by Scoutski** [comment]
Hi @sofiapoh - firstly, thanks for all the work you've done on this project, really appreciate it.

I've been trying to get react-live working in IE11 as well and unfortunately at the earliest stages it seems to break due to a nested dependency through `buble` called `acorn-jsx` which includes a `class` reference in it's export. Since IE11 can't read the class keyword, it breaks the entire site.

I have made a comment on `acorn-jsx` asking if it can be fully transpiled so that it works in IE11 and for now I assume that will be enough to get it working in IE11, if not, I'd be happy to do more if there's something inside react-live causing issues.
https://github.com/RReverser/acorn-jsx/issues/98

Thanks

**Comment by kate-hall** [comment]
@Scoutski I'm having the same issue, and have been banging my head against this issue for a while, running `acorn-jsx` through a transpiler on my end doesn't seem to be working no matter what I do.
