### ISSUE TITLE
What does "production-focused" mean?

### ISSUE THREAD

**Issue by zxti** [FormidableLabs/react-live#140]
Really neat project!  I'm just curious what the "production-focused" tagline means exactly, though (genuine question!).

**Comment by sofiapoh** [comment]
Back when we we're still actively supporting [`component-playground`](https://github.com/FormidableLabs/component-playground) we made a distinction of `react-live` being more suitable for production grade applications due to it's flexibility and smaller bundle size. Now that we're not really maintaining `component-playground` anymore it doesn't make so much sense! I'll make a point to come up with a a new tagline.
