### ISSUE TITLE
what are breaking changes in v2?

### ISSUE THREAD

**Issue by oprogramador** [FormidableLabs/react-live#187]
I cannot see any breaking changes in https://github.com/FormidableLabs/react-live/releases/tag/v2.0.0

**Comment by sofiapoh** [comment]
There's nothing too obviously breaking but we ended up changing from our own editor to `react-simple-code-editor` which changed how the editor worked in some cases compared to `1.x.x` versions so if a user was relying on some of this behaviour it _could_ lead to their app breaking. This lead to change how the app was themed as well so that's why we released a major version.

**Comment by oprogramador** [comment]
For me the new version doesn't work correctly.
<img width="1361" alt="Screenshot 2020-03-10 at 17 37 45" src="https://user-images.githubusercontent.com/8701039/76336318-20345980-62f6-11ea-90ca-05c1428bd231.png">
<img width="339" alt="Screenshot 2020-03-10 at 17 37 57" src="https://user-images.githubusercontent.com/8701039/76336412-42c67280-62f6-11ea-9c2a-0c30100804e0.png">
<img width="1028" alt="Screenshot 2020-03-10 at 17 38 23" src="https://user-images.githubusercontent.com/8701039/76336426-4823bd00-62f6-11ea-8d9d-6155bb09ec61.png">

The styles are broken and in this example https://beghp.github.io/gh-pages-rc-10/docs/examples/dots it's impossible to scroll down.

**Comment by sofiapoh** [comment]
I'm not sure if I understand your problem and I couldn't see a problem with scrolling on your example. Are you able to provide a small reproduction in a CodeSandbox?
