### ISSUE TITLE
Don't rerender the preview if there is an error.

### ISSUE THREAD

**Issue by kentcdodds** [FormidableLabs/react-live#20]
I think it'd be nice if when a user makes a typo (or while they're typing), the rendered preview does not rerender if the editor has an error.

Thoughts?

**Comment by burge-is** [comment]
https://stackoverflow.com/questions/23123138/perform-debounce-in-react-js
Using debounce on the `onChange()` is what immediately comes to mind.

**Comment by kentcdodds** [comment]
Thanks for the tip. Additionally, I'd like people to be able to still see the most recent result even if they have stopped typing to read the error message

**Comment by philpl** [comment]
You mean it should keep the last intact preview?

It does have this behaviour for inline mode. For noInline mode where you call render we have to clear the preview as it might render sth after a delay.

Maybe I should add a prop that prevents the default clearing behaviour?

**Comment by kentcdodds** [comment]
Yeah, that'd be super. I think it would improve user experience.

**Comment by kentcdodds** [comment]
I'm not going to work on this and I don't think we'd bother upgrading even if it were implemented so I think I'll just close this :)

**Comment by elliotdickison** [comment]
@kitten This is a feature I need, I'd be interested in contributing. I have a prototype working locally. What would you prefer to name the prop? I'm thinking `clearPreviewOnError` as a prop on `Provider`. I'd also like to get it working consistently between `noInline` true/false, although that would mean a breaking-ish change since they currently default to different behaviors.

**Comment by kylemath** [comment]
@elliotdickison you have a nice way of solving this? I am annoyed with the way the preview moves the code around here:
https://github.com/kylemath/p5.eegedu
