### ISSUE TITLE
help，a question about overflow

### ISSUE THREAD

**Issue by Mr-zsy** [FormidableLabs/react-live#209]
How can i do？when the code beyond the textarea elements‘ borders，and i can’t edit it。Please，help me！

**Comment by RoachaelRoadmunk** [comment]
I am also noticing this issue.

For more details on what I am seeing: When I set a fixed height to the code preview, I can't edit any of the lines that aren't visible when landing on the page (ie any lines that I need to scroll too). Looks like the textarea becomes only the height of the editor rather than the heigh of its contents which are overflowing.

Is there a pattern we should be following to enable this?

**Comment by sofiapoh** [comment]
I'm not sure if I understand the issue exactly, could you provide an example on [CodeSandbox](https://codesandbox.io)? It will be easier for me to help with a reproduction!

**Comment by Mr-zsy** [comment]
I set a 'div' element out of the 'LiveEditor' to achieve it, like this
```
<div style={{overflow: 'auto'}}>
    <LiveEditor/>
</div>
```

**Comment by rwieruch** [comment]
Can confirm. Giving the LiveEditor the following style breaks everything that's outside of the height:

```
              overflow: 'auto',
              height: '255px',
```

**Comment by appanasantosh** [comment]
I am also facing the same issue. When we set the editor with some defined height then the style breaks and unable to edit it.
