### ISSUE TITLE
Hooks trigger error

### ISSUE THREAD

**Issue by Kais3rP** [FormidableLabs/react-live#237]
Is it just me that receive a React error about "Hooks execution outside of the body of a Component" if I try to dynamically write a function with a React hook? I tried that both on the demo playground and on a codesandbox, and in both cases it triggers the error.

**Comment by StevenCreates** [comment]
@Kais3rP  I just get errors in general when using any react hook. What a bummer 😢

**Comment by jpdriver** [comment]
hey @Kais3rP 👋🏻 

Hooks are fully supported, but you may have hit an issue trying to use a hook that isn't in scope?

By default you only have `React` in scope, so instead of doing something like `useState` you need to do `React.useState`.

Try the below on our [demo page](https://react-live.netlify.app)
```
function Example() {
  // Declare a new state variable, which we'll call "count"
  const [count, setCount] = React.useState(0);

  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>
        Click me
      </button>
    </div>
  );
}
```

feel free to re-open if you have any problems
