### ISSUE TITLE
SSR not working anymore since 2.3.0

### ISSUE THREAD

**Issue by hrasoa** [FormidableLabs/react-live#272]
I created a small app with razzle here: https://github.com/hrasoa/react-live
```jsx
import React from 'react';
import {
  LiveProvider,
  LivePreview
} from 'react-live'

const App = () => (
  <LiveProvider code="<strong>Hello World!</strong>">
    <LivePreview />
  </LiveProvider>
);

export default App;
```

With ```react-live@2.2.3```

```html
<div id="root"><div><strong>Hello World!</strong></div></div>
```

From ```react-live@2.3.0```
```html
<div id="root"><div></div></div>
```

**Comment by jpdriver** [comment]
hey @hrasoa -- thanks for opening this issue and for providing a sample app.

unfortunately due to changes introduced in `2.3.0` (the adoption of `useEffect` and `useState` hooks in `<LiveProvider />`), `react-live` no longer supports SSR.

however, this only affects the initial HTML sent from your server. once your app rehydrates on the client-side, everything will mount and work as expected.

**Comment by tujoworker** [comment]
Here is a [PR](https://github.com/FormidableLabs/react-live/pull/322) that supports SSR ✨

**Comment by tujoworker** [comment]
Here is a new [PR](https://github.com/FormidableLabs/react-live/pull/414) that adds SSR support.
