### ISSUE TITLE
Reset Editor Code

### ISSUE THREAD

**Issue by DimaMirana** [FormidableLabs/react-live#279]
Is there any props or function where you can reset the editor to default code value?

**Comment by equinusocio** [comment]
If you want, we did a custom implementation to reset the code here
https://github.com/wonderflow-bv/design/blob/staging/src/components/live-code/live-code.tsx#L119

We wrapped the component and passed the `onRestore` callback that reset the original code.

**Comment by jpdriver** [comment]
hey @DimaMirana -- this is something you should be able to implement with a CustomEditor. Have a look at our [Storybook stories](https://github.com/FormidableLabs/react-live/blob/666b817d1858f7419b970dae4f7a28713a603213/stories/Live.js#L149-L162) for an example.

Unfortunately this isn't something we can add to the default Editor because then we'd be forcing UI patterns on everyone using the lib 😅

**Comment by stevenocchipinti** [comment]
I would imagine once dynamically updating the code works again (#271) this would be easy to implement with the `code` prop and local state.
