### ISSUE TITLE
Feature request: A button to copy code.

### ISSUE THREAD

**Issue by VibhorJaiswal** [FormidableLabs/react-live#280]
As of now, we have to manually select and copy the code.

I would like to contribute a feature by which code can be copied by a single click of a button.

**Comment by jpdriver** [comment]
hey @VibhorJaiswal -- this is something you should be able to implement with a CustomEditor. Have a look at our [Storybook stories](https://github.com/FormidableLabs/react-live/blob/666b817d1858f7419b970dae4f7a28713a603213/stories/Live.js#L149-L162) for an example.

Unfortunately this isn't something we can add to the default Editor because then we'd be forcing UI patterns on everyone using the lib 😅
