### ISSUE TITLE
Why not use `innerText` instead of `htmlToPlain` by self in `Editor/index.js`

### ISSUE THREAD

**Issue by imcuttle** [FormidableLabs/react-live#47]
![image](https://user-images.githubusercontent.com/13509258/32411339-09ea64ac-c213-11e7-885f-fe74d745cf9d.png)

https://github.com/FormidableLabs/react-live/blob/2f010fe890fc1b3acc5af17c20ee470e094e6efb/src/components/Editor/index.js#L33
This action can shrink the dependencies, excludes `unescape`

**Comment by philpl** [comment]
@imcuttle originally, I found some edge cases where it didn't seem to work, but indeed it's probable that revisiting this could bring a slight improvement. I'll test whether all browsers will yield the correct results, without the need to reformat it. I think this had something to do with whitespace/newline formatting. I think in some cases some `\r\n\f\t ` characters got lost.

On the other hand, this won't have any significant impact on the bundle size, since mostly buble, and next in line prism, make up most of that. So I'm not sure whether it's even to be considered a high priority.

**Comment by imcuttle** [comment]
wow, thx!

**Comment by philpl** [comment]
@imcuttle let keep this open for now 😅

I’d be happy to investigate it in the future and either prove or disprove its feasibility

**Comment by kitten** [comment]
Might go away with #77
