### ISSUE TITLE
Styled-jsx instead of styled-component

### ISSUE THREAD

**Issue by Flo-Slv** [FormidableLabs/react-live#72]
Hi!

Which is the better way to use styled-jsx (zeit/next project) instead of styled-component.

Indeed, i have this warning.

```
const challengeDescription = this.state.description;
const challengeDetails = this.state.details;

const scope = { challengeDescription, challengeDetails };

    const code = `
      render(
        <div className="root">
        <style jsx>{\`
          .root {
            color: green;
          }
        \`}</style>
        </div>
      )
    `;
   
<LiveProvider code={code} scope={scope} noInline>
   <Row>
      <Col sm={5}>
          <LiveEditor />
          <LiveError />
       </Col>
       <Col sm={7}>
          <LivePreview />
        </Col>
    </Row>
</LiveProvider>
```

> warning.js?6327:33 Warning: Received `true` for a non-boolean attribute `jsx`.
If you want to write it to the DOM, pass a string instead: jsx="true" or jsx={value.toString()}.
    in style
    in div
    in ErrorBoundary (created by LivePreview)
    in div (created by LivePreview)

**Comment by kitten** [comment]
`styled-jsx` doesn't work without its Babel plugin; Since your code runs in a sandboxed environment and is transpiled completely separately using Bublé, you're not seeing the result you'd normally expect.

There's some issues in this repo where ppl hook Babel Standalone into react-live (at the cost of the bundlesize of course). That might work in your case :+1:
