### ISSUE TITLE
styled-components style expression won't work by default

### ISSUE THREAD

**Issue by alansouzati** [FormidableLabs/react-live#94]
Sending this as the code to `react-live`:

```
const code = `
  const Header = styled.div\`
    color: palevioletred;
    font-size: 18px;
    ${props => (props.big ? "font-size: 24px" : "font-size: 18px;")}
  \`

  render(<Header big={true}>{headerProps.text}</Header>)
`;
```

results in a transformation like this:

```
const Header = styled.div`
    color: palevioletred;
    font-size: 18px;
    function (props) {
  return props.big ? "font-size: 24px" : "font-size: 18px;";
}
  `
```

## Expected Result

react-live to support template literal expressions

## How to reproduce ?

https://codesandbox.io/s/jpkk6vjjow

**Comment by kitten** [comment]
You're writing your code inside a template literal string, and inside your code is a tagged template literal for styled-components.

You're already escaping the inner back ticks with a backslash, but the interpolation for your Style Component isn't escaped so it's stringified into the _outer_ template that's assigned to your code variable.

Just escape the interpolations dollar sign as well and it'll work 🙂 Keep close attention to the output or go to StackOverflow for these types of issues please, since issue trackers are often not reserved for generic JS questions 😊

Let me know if there's anything else

**Comment by alansouzati** [comment]
thanks for heads the up, and yes it works 👍
